apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium
  namespace: default
  annotations:
    io.cilium/lb-ipam-ips: "192.168.1.101"
    lbipam.cilium.io/sharing-key: "home-lan-shared"
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
