apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-pool
  namespace: default
spec:
  blocks:
    - start: "192.168.1.101"
      stop: "192.168.1.102"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: home-l2-policy
  namespace: default
spec:
  externalIPs: true
  loadBalancerIPs: true
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchLabels: {}
  interfaces:
  - ^eth1
