apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrserver-pvc
  namespace: torrserver
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
