apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "UTC"
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: WEBPASSWORD
            - name: PIHOLE_DNS_
              value: "1.1.1.1;1.0.0.1"
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pihole-etc
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
            - name: custom-dns
              mountPath: /etc/dnsmasq.d/02-custom-dns.conf
              subPath: 02-custom-dns.conf
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-etc-pvc
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq-pvc
        - name: custom-dns
          configMap:
            name: pihole-custom-dns
