apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skarj/Homelab.git
    targetRevision: HEAD
    path: workloads/external-dms
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
