apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn-otel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skarj/learn-otel.git
    targetRevision: main
    path: deploy/overlays/home
  destination:
    server: https://kubernetes.default.svc
    namespace: learn-otel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
