apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-agent-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skarj/ai-agents.git
    targetRevision: main
    path: agentic-sre/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: torrserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
